$(document).ready(function() {
  $('#preload').remove()
  $('body').removeClass('loading')
  $('.close-dimmer').click(function() {
    $(this).closest('body').addClass('dimmer-open')
  })

  $('.close-menu').click(function() {
    $(this).closest('body').removeClass('dimmer-open')
  })

  $('.imgLiquid').imgLiquid({
    verticalAlign: 'top'
  })
  $('.imgLiquidNoFill').imgLiquid({
    fill: false,
    horizontalAlign: 'center'
  })
  $('.image-compound__image').children('img').removeAttr('style')
  $('.image_front').children('img').removeAttr('style')
  $('#carousel-lbx').owlCarousel({
    items: 1,
    lazyLoad: true,
    navText: ['<i></i><i></i>', '<i></i><i></i>'],
    loop: true,
    nav: true,
    dots: false,
    margin: 10,
    pullDrag: false
  })

  $('.datepicker').datepicker({
    format: 'dd-mm-yyyy',
    language: 'es'
  })
  var slider = document.querySelectorAll('section')[0]
  const topBar = document.getElementById('top')
  const topHeader = document.getElementsByClassName('top-header')[0]
  topHeader.classList.add('static')
  $(window).scroll(function() {
    if (slider.clientHeight > 115) {
      topHeader.classList.remove('static')
      if ($(window).scrollTop() >= (slider.clientHeight - 80)) {
        topBar.classList.add('float')
      } else {
        if (topBar.classList.contains('float')) {
          topBar.classList.remove('float')
        }
      }
    }
  })
  AOS.init()

  $('#from_datos').submit(function(e) {
    e.preventDefault()
    $(this).parent().fadeOut()
    $('#ficha').fadeIn()
    $('#step_datos').removeClass('active')
    $('#step_ficha').addClass('active')
  })

  $('#carousel__home')
})

var timelineSwiper = new Swiper('.timeline .swiper-container', {
  direction: 'vertical',
  initialSlide: 1,
  loop: false,
  speed: 1600,
  pagination: '.swiper-pagination',
  paginationBulletRender: function (swiper, index, className) {
    var year = document.querySelectorAll('.swiper-slide')[index].getAttribute('data-year')
    return '<span class="' + className + '">' + year + '</span>'
  },
  paginationClickable: true,
  nextButton: '.swiper-button-next',
  prevButton: '.swiper-button-prev',
  breakpoints: {
    768: {
      direction: 'vertical'
    }
  }
})

$('a[href*="#"]')
  .not('[href="#"]')
  .not('[href="#0"]')
  .click(function(event) {
    if (location.pathname.replace(/^\//, '') == this.pathname.replace(/^\//, '') && location.hostname == this.hostname) {
      var target = $(this.hash)
      target = target.length ? target : $('[name=' + this.hash.slice(1) + ']')
      if (target.length) {
        event.preventDefault()
        $('html, body').animate({
          scrollTop: target.offset().top
        }, 1000, function() {
          var $target = $(target)
          $target.focus()
          if ($target.is(':focus')) {
            return false
          } else {
            $target.attr('tabindex', '-1')
            $target.focus()
          };
        })
      }
    }
  })

var historySwiper = new Swiper('.history .swiper-container', {
  direction: 'vertical',
  speed: 400,
  pagination: '.swiper-pagination-years',
  paginationBulletRender: function (swiper, index, className) {
    var year = document.querySelectorAll('.swiper-slide')[index].getAttribute('data-year')
    return '<span class="' + className + '">' + year + '</span>'
  },
  paginationClickable: true
})
// -----------------------------------------------------------------------------------
// http://wowslider.com/
// JavaScript Wow Slider is a free software that helps you easily generate delicious
// slideshows with gorgeous transition effects, in a few clicks without writing a single line of code.
// Generated by WOW Slider 8.8
//
//* **********************************************
// Obfuscated by Javascript Obfuscator
// http://javascript-source.com
//* **********************************************
function ws_parallax(k, g, a) { var c = jQuery; var f = c(this); var d = a.find('.ws_list'); var b = k.parallax || 0.25; var e = c('<div>').css({ position: 'absolute', top: 0, left: 0, width: '100%', height: '100%', overflow: 'hidden' }).addClass('ws_effect ws_parallax').appendTo(a); function j(l) { return Math.round(l * 1000) / 1000 } var i = c('<div>').css({ position: 'absolute', left: 0, top: 0, overflow: 'hidden', width: '100%', height: '100%', transform: 'translate3d(0,0,0)' }).appendTo(e); var h = i.clone().appendTo(e); this.go = function(l, r, p) { var s = c(g.get(r)); s = { width: s.width(), height: s.height(), marginTop: s.css('marginTop'), marginLeft: s.css('marginLeft') }; p = p ? 1 : -1; var n = c(g.get(r)).clone().css(s).appendTo(i); var o = c(g.get(l)).clone().css(s).appendTo(h); var m = a.width() || k.width; var q = a.height() || k.height; d.hide(); wowAnimate(function(v) { v = c.easing.swing(v); var x = j(p * v * m), u = j(p * (-m + v * m)), t = j(-p * m * b * v), w = j(p * m * b * (1 - v)); if (k.support.transform) { i.css('transform', 'translate3d(' + x + 'px,0,0)'); n.css('transform', 'translate3d(' + t + 'px,0,0)'); h.css('transform', 'translate3d(' + u + 'px,0,0)'); o.css('transform', 'translate3d(' + w + 'px,0,0)') } else { i.css('left', x); n.css('margin-left', t); h.css('left', u); o.css('margin-left', w) } }, 0, 1, k.duration, function() { e.hide(); n.remove(); o.remove(); f.trigger('effectEnd') }) } };// -----------------------------------------------------------------------------------
// http://wowslider.com/
// JavaScript Wow Slider is a free software that helps you easily generate delicious
// slideshows with gorgeous transition effects, in a few clicks without writing a single line of code.
// Generated by WOW Slider 8.8
//
//* **********************************************
// Obfuscated by Javascript Obfuscator
// http://javascript-source.com
//* **********************************************

let slides = document.getElementById('next_slides').children
let imagesArray = []
for (let i = 0; i < slides.length; i++) {
  const element = slides[i]
  let itemObj = {
    src: element.href,
    title: element.title
  }
  imagesArray.push(itemObj)
}

jQuery('#wowslider-container1').wowSlider({ effect: 'parallax',
  prev: '',
  next: '',
  duration: 20 * 100,
  delay: 20 * 100,
  width: 570,
  height: 460,
  autoPlay: true,
  autoPlayVideo: false,
  playPause: false,
  stopOnHover: false,
  loop: false,
  bullets: 1,
  caption: true,
  captionEffect: 'parallax',
  controls: false,
  controlsThumb: false,
  responsive: 2,
  fullScreen: false,
  gestures: 2,
  onBeforeStep: 0,
  images: imagesArray
})
